### PR TITLE
Migrate to null-safety

### LINKED ISSUE #9: Null safety version
Hello,

Do you have any plans to migrate this package to support null safety?

Thanks!

### PR DESCRIPTION
**Pull request by ghpranav**
Should fix #9

### CODE REVIEW

**Comment by ghpranav** [comment]
@sur950 sorry for the force pushes. Now the changes have been completely tested with the given example code & everything seems to be working without any breaking changes.

**Comment by sur950** [comment]
Thanks for the PR @ghpranav , I will verify & will merge it tomorrow

**Comment by sur950** [comment]
@ghpranav I think you have used `charset_converter` package for Encode and decode of charsets. But this is only supported for Android & IOS, Our aim should be focusing for most of the platforms.

If you have time, Could you help me in finding any other alternative plugin/package for ```charset_converter```

Thanks!

**Comment by ghpranav** [comment]
I did try searching for other alternatives, but none of them seemed to be migrated to null-safety yet. I will let you know if I find one

**Comment by ghpranav** [comment]
@sur950 please check now. Also, if you can somehow remove the dependency on `dart:isolate` then your package can support Web as well.

**Pull request merged**
